In [2]:
import pandas as pd

In [61]:
df = pd.read_excel(r'D:\blinkit_project\docs\blinkit.xlsx')

In [62]:
df

,customer_id,customer_name,email,phone,address,area,pincode,registration_date,customer_segment,total_orders,avg_order_value
0,31813,Indrajit Pau,wakeetasehgal@example.com,911785834174,"66, Vora Chowk\nMaheshtala 376030",Sultan Pur Majra,666762,04-10-24,Regular,18,1230.75
1,31826,Ekiya Pau,fbedi@example.com,919364120886,"H.No. 336\nLad Zila, Hajipur-409871",Chinsurah,201602,11-29-23,New,18,752.78
2,61020,Onkar Suresh,rudradeshpande@example.com,918421031341,"88/40, Bora Zila, Phusro-161515",Kurnool,345635,07-27-24,New,19,1703.16
3,75482,Jeet Gandhi,amrita05@example.net,916683687947,"95/861, Jaggi, Sikar-343285",Korba,298093,09-19-24,Regular,13,1938.38
4,119099,Zansi Parsa,neha08@example.com,912032907631,"H.No. 40, Gopal Ganj, Bidar 854350",Kavali,692517,08-01-23,Inactive,20,637.35
...,...,...,...,...,...,...,...,...,...,...,...
2495,99734256,Ishwar Nair,ambleira@example.com,916815943299,"20/227, Sant Nagar\nDanapur-130747",Ratlam,477588,06-04-24,Premium,1,301.12
2496,99772709,Xiti Jaggi,girishgour@example.net,915944903403,"39/76, Yogi Chowk, Jalna-806277",Tadepalligudem,798755,09-03-23,Regular,11,1905.19
2497,99784559,Laban Chopra,gayathri37@example.net,916462666703,672\nBhatia Road\nRampur 543886,Allahabad,407983,07-14-24,Inactive,18,218.41
2498,99824171,Vasatika Ram,tkhare@example.com,912587842615,34/661\nDivan Zila\nChandrapur-092281,Thoothukudi,298856,04-15-24,Inactive,1,1663.58
2499,99893898,Vedant Master,forumwable@example.com,916100269271,"123, Manda Circle, Dehradun 286985",Berhampore,893327,11-22-23,New,16,365.40

In [97]:
df.head(10)

,customer_id,customer_name,email,phone,address,area,pincode,registration_date,customer_segment,total_orders,avg_order_value
0,31813,Indrajit Pau,wakeetasehgal@example.com,911785834174,"66, Vora Chowk\nMaheshtala 376030",Sultan Pur Majra,666762,04-10-24,Regular,18,1230.75
1,31826,Ekiya Pau,fbedi@example.com,919364120886,"H.No. 336\nLad Zila, Hajipur-409871",Chinsurah,201602,11-29-23,New,18,752.78
2,61020,Onkar Suresh,rudradeshpande@example.com,918421031341,"88/40, Bora Zila, Phusro-161515",Kurnool,345635,07-27-24,New,19,1703.16
3,75482,Jeet Gandhi,amrita05@example.net,916683687947,"95/861, Jaggi, Sikar-343285",Korba,298093,09-19-24,Regular,13,1938.38
4,119099,Zansi Parsa,neha08@example.com,912032907631,"H.No. 40, Gopal Ganj, Bidar 854350",Kavali,692517,08-01-23,Inactive,20,637.35
5,188838,Idika Basu,deepakhanna@example.com,914955579642,"67, Karan Chowk\nKatihar 496332",Madanapalle,566155,07-16-24,Inactive,12,799.11
6,191616,Brijesh Tata,yadavipatla@example.org,918144382068,"19/151, Bera Nagar, Surendranagar Dudhrej-068367",Pallavaram,587079,04-27-23,Regular,4,1053.70
7,211163,Hiral Baral,bhavsaryagnesh@example.com,911312775966,"H.No. 11\nSharma Chowk, Jhansi-302598",Satna,50152,06-10-24,Regular,9,1169.11
8,243838,Sudiksha Nagar,chandanikrish@example.net,913688907644,H.No. 58\nCherian Zila\nDhule 851724,Visakhapatnam,865844,05-16-24,New,11,1158.27
9,376144,Ira Chhabra,caleb02@example.com,914254514422,H.No. 39\nSarkar Path\nKarawal Nagar-657936,Anantapuram,627253,12-19-23,Regular,13,1784.32

In [57]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 268 entries, 0 to 267
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   product_id         268 non-null    int64
 1   product_name       268 non-null    object
 2   category           268 non-null    category
 3   brand              268 non-null    category
 4   price              268 non-null    float64
 5   mrp                268 non-null    float64
 6   margin_percentage  268 non-null    float64
 7   shelf_life_days    268 non-null    int64
 8   min_stock_level    268 non-null    int64
 9   max_stock_level    268 non-null    int64
dtypes: category(2), float64(3), int64(4), object(1)
memory usage: 28.2+ KB

In [68]:
df[['area', 'customer_segment']] = df[['area', 'customer_segment']].astype('category')

In [79]:
df['pincode'] = df['pincode'].astype(str).str.zfill(6)

In [80]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2500 entries, 0 to 2499
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   customer_id        2500 non-null   int64
 1   customer_name      2500 non-null   object
 2   email              2500 non-null   object
 3   phone              2500 non-null   object
 4   address            2500 non-null   object
 5   area               2500 non-null   category
 6   pincode            2500 non-null   object
 7   registration_date  2500 non-null   datetime64[ns]
 8   customer_segment   2500 non-null   category
 9   total_orders       2500 non-null   int64
 10  avg_order_value    2500 non-null   float64
dtypes: category(2), datetime64[ns](1), float64(1), int64(2), object(5)
memory usage: 194.0+ KB

In [7]:
df.describe(include='all')

,customer_id,customer_name,email,phone,address,area,pincode,registration_date,customer_segment,total_orders,avg_order_value
count,2.500000e+03,2500,2500,2500,2500,2500,2500,2500,2500,2500.000000,2500.000000
unique,NaN,2491,2496,2500,2500,316,2494,NaN,4,NaN,NaN
top,NaN,Gaurang Grewal,ilad@example.net,911785834174,"66, Vora Chowk\nMaheshtala 376030",Jalna,368657,NaN,Regular,NaN,NaN
freq,NaN,2,2,1,1,18,2,NaN,639,NaN,NaN
mean,4.989961e+07,NaN,NaN,NaN,NaN,NaN,NaN,2024-01-15 18:06:20.160000,NaN,10.491600,1102.375836
min,3.181300e+04,NaN,NaN,NaN,NaN,NaN,NaN,2023-03-16 00:00:00,NaN,1.000000,200.430000
25%,2.402443e+07,NaN,NaN,NaN,NaN,NaN,NaN,2023-08-21 18:00:00,NaN,6.000000,631.817500
50%,5.000044e+07,NaN,NaN,NaN,NaN,NaN,NaN,2024-01-22 12:00:00,NaN,10.000000,1118.650000
75%,7.595459e+07,NaN,NaN,NaN,NaN,NaN,NaN,2024-06-12 06:00:00,NaN,16.000000,1565.400000
max,9.989390e+07,NaN,NaN,NaN,NaN,NaN,NaN,2024-11-04 00:00:00,NaN,20.000000,1999.830000
std,2.919266e+07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.805533,523.043183

In [10]:
df.isnull().sum()

customer_id          0
customer_name        0
email                0
phone                0
address              0
area                 0
pincode              0
registration_date    0
customer_segment     0
total_orders         0
avg_order_value      0
dtype: int64

### NO NULL VALUES IN CUSTOMERS DATE

In [6]:
df.columns

Index(['customer_id', 'customer_name', 'email', 'phone', 'address', 'area',
       'pincode', 'registration_date', 'customer_segment', 'total_orders',
       'avg_order_value'],
      dtype='object')

In [56]:
df = pd.read_excel(r'D:\blinkit_project\docs\blinkit.xlsx',sheet_name='customer_feedback')

df

,feedback_id,order_id,customer_id,rating,feedback_text,feedback_category,sentiment,feedback_date
0,7669412,7997347191,31813,3,Product was damaged during delivery.,App Experience,Negative,07-11-24
1,950262,5698803942,31813,1,Customer service was not helpful.,Delivery,Negative,10-10-24
2,2668183,4961370923,61020,4,"Average experience, could improve.",Delivery,Neutral,02-04-24
3,6210544,4283802879,61020,4,Will definitely order again.,Delivery,Positive,05-10-23
4,6378461,3367452972,61020,3,"It was okay, nothing special.",App Experience,Neutral,08-31-24
...,...,...,...,...,...,...,...,...
4995,1457389,2962076108,99824171,4,"Delivery was fine, but the product could be be...",Delivery,Neutral,06-13-24
4996,2865376,3963207709,99893898,3,"Nothing to complain about, but nothing excepti...",Delivery,Neutral,01-04-24
4997,6435438,4054828941,99893898,4,Great prices and fast delivery!,Delivery,Positive,12-15-23
4998,819181,8371900149,99893898,4,Will definitely order again.,App Experience,Positive,08-31-24
4999,7789018,1860491452,99893898,5,Great prices and fast delivery!,App Experience,Positive,04-18-24

In [57]:
df.head(10)

,feedback_id,order_id,customer_id,rating,feedback_text,feedback_category,sentiment,feedback_date
0,7669412,7997347191,31813,3,Product was damaged during delivery.,App Experience,Negative,07-11-24
1,950262,5698803942,31813,1,Customer service was not helpful.,Delivery,Negative,10-10-24
2,2668183,4961370923,61020,4,"Average experience, could improve.",Delivery,Neutral,02-04-24
3,6210544,4283802879,61020,4,Will definitely order again.,Delivery,Positive,05-10-23
4,6378461,3367452972,61020,3,"It was okay, nothing special.",App Experience,Neutral,08-31-24
5,8510571,2055388266,119099,4,Good selection of products.,Product Quality,Positive,06-23-23
6,7045900,6660740926,119099,3,I had a bad experience.,Delivery,Negative,05-24-24
7,9132205,6538760883,119099,3,The order was incorrect.,App Experience,Negative,04-19-24
8,8112211,4704980993,119099,4,Good selection of products.,App Experience,Positive,05-24-24
9,4219934,3447085029,188838,3,"It was okay, nothing special.",App Experience,Neutral,04-25-23

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   feedback_id        5000 non-null   int64
 1   order_id           5000 non-null   int64
 2   customer_id        5000 non-null   int64
 3   rating             5000 non-null   int64
 4   feedback_text      5000 non-null   object
 5   feedback_category  5000 non-null   object
 6   sentiment          5000 non-null   object
 7   feedback_date      5000 non-null   object
dtypes: int64(4), object(4)
memory usage: 312.6+ KB

In [58]:
df['feedback_date'] = pd.to_datetime(df['feedback_date'], errors='coerce')
df['feedback_category'] = df['feedback_category'].astype('category')
df['sentiment'] = df['sentiment'].astype('category')

C:\Users\damma\AppData\Local\Temp\ipykernel_4928\280388703.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['feedback_date'] = pd.to_datetime(df['feedback_date'], errors='coerce')

In [11]:
df['rating'] = df['rating'].astype('float32')

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   feedback_id        5000 non-null   int64
 1   order_id           5000 non-null   int64
 2   customer_id        5000 non-null   int64
 3   rating             5000 non-null   float32
 4   feedback_text      5000 non-null   object
 5   feedback_category  5000 non-null   category
 6   sentiment          5000 non-null   category
 7   feedback_date      5000 non-null   datetime64[ns]
dtypes: category(2), datetime64[ns](1), float32(1), int64(3), object(1)
memory usage: 225.1+ KB

In [13]:
df.describe(include='all')

,feedback_id,order_id,customer_id,rating,feedback_text,feedback_category,sentiment,feedback_date
count,5.000000e+03,5.000000e+03,5.000000e+03,5000.000000,5000,5000,5000,5000
unique,NaN,NaN,NaN,NaN,25,4,3,NaN
top,NaN,NaN,NaN,NaN,The product met my expectations.,Delivery,Neutral,NaN
freq,NaN,NaN,NaN,NaN,386,1271,1738,NaN
mean,5.013616e+06,5.029129e+09,5.009685e+07,3.344400,NaN,NaN,NaN,2024-01-08 12:53:16.800000
min,9.470000e+02,6.046500e+04,3.181300e+04,1.000000,NaN,NaN,NaN,2023-03-16 00:00:00
25%,2.576690e+06,2.531421e+09,2.404314e+07,3.000000,NaN,NaN,NaN,2023-08-16 18:00:00
50%,5.005833e+06,5.074378e+09,4.997808e+07,4.000000,NaN,NaN,NaN,2024-01-07 00:00:00
75%,7.486478e+06,7.488579e+09,7.621215e+07,4.000000,NaN,NaN,NaN,2024-06-03 00:00:00
max,9.999293e+06,9.998298e+09,9.989390e+07,5.000000,NaN,NaN,NaN,2024-11-04 00:00:00
std,2.857341e+06,2.863533e+09,2.919082e+07,1.189826,NaN,NaN,NaN,NaN

In [14]:
df.isnull().sum()

feedback_id          0
order_id             0
customer_id          0
rating               0
feedback_text        0
feedback_category    0
sentiment            0
feedback_date        0
dtype: int64

### NO NULL VALUES IN CUSTOMER_FEEDBACK DATA ##

In [15]:
df.columns

Index(['feedback_id', 'order_id', 'customer_id', 'rating', 'feedback_text',
       'feedback_category', 'sentiment', 'feedback_date'],
      dtype='object')

In [16]:
df = pd.read_excel(r'D:\blinkit_project\docs\blinkit.xlsx',sheet_name='delivery')

df

,order_id,delivery_partner_id,promised_time,actual_time,delivery_time_minutes,distance_km,delivery_status,reasons_if_delayed
0,60465,58998,10/23/24 5:33,10/23/24 5:39,5,3.97,On Time,Traffic
1,2237858,97945,4/2/23 4:00,4/2/23 4:02,3,3.86,On Time,Traffic
2,3101265,20246,5/23/24 3:36,5/23/24 3:40,3,2.45,On Time,Traffic
3,5120698,48582,6/9/23 12:24,6/9/23 12:40,15,4.82,Slightly Delayed,Traffic
4,5512907,44545,4/30/23 21:11,4/30/23 21:26,15,0.59,Slightly Delayed,Traffic
...,...,...,...,...,...,...,...,...
4995,9993542681,73532,5/23/23 4:25,5/23/23 4:41,15,4.21,Slightly Delayed,Traffic
4996,9996182478,48495,4/18/23 13:30,4/18/23 13:30,0,2.97,On Time,NaN
4997,9997121955,27103,4/21/24 0:18,4/21/24 0:15,-3,2.37,On Time,NaN
4998,9997994965,28092,12/27/23 14:19,12/27/23 14:17,-3,0.99,On Time,NaN
4999,9998297778,15629,9/22/23 17:26,9/22/23 17:26,1,4.71,On Time,Traffic

In [17]:
df.head(10)

,order_id,delivery_partner_id,promised_time,actual_time,delivery_time_minutes,distance_km,delivery_status,reasons_if_delayed
0,60465,58998,10/23/24 5:33,10/23/24 5:39,5,3.97,On Time,Traffic
1,2237858,97945,4/2/23 4:00,4/2/23 4:02,3,3.86,On Time,Traffic
2,3101265,20246,5/23/24 3:36,5/23/24 3:40,3,2.45,On Time,Traffic
3,5120698,48582,6/9/23 12:24,6/9/23 12:40,15,4.82,Slightly Delayed,Traffic
4,5512907,44545,4/30/23 21:11,4/30/23 21:26,15,0.59,Slightly Delayed,Traffic
5,7550508,38073,10/20/23 11:06,10/20/23 11:06,-1,2.21,On Time,NaN
6,8701796,41266,8/19/24 19:14,8/19/24 19:23,9,4.97,Slightly Delayed,Traffic
7,9408428,76392,8/30/23 13:54,8/30/23 13:50,-4,2.17,On Time,NaN
8,10161194,58293,12/24/23 23:28,12/24/23 23:30,3,4.44,On Time,Traffic
9,10448052,47308,8/5/23 10:21,8/5/23 10:25,5,4.53,On Time,Traffic

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 8 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   order_id               5000 non-null   int64
 1   delivery_partner_id    5000 non-null   int64
 2   promised_time          5000 non-null   object
 3   actual_time            5000 non-null   object
 4   delivery_time_minutes  5000 non-null   int64
 5   distance_km            5000 non-null   float64
 6   delivery_status        5000 non-null   object
 7   reasons_if_delayed     3098 non-null   object
dtypes: float64(1), int64(3), object(4)
memory usage: 312.6+ KB

In [19]:
df.describe(include='all')

,order_id,delivery_partner_id,promised_time,actual_time,delivery_time_minutes,distance_km,delivery_status,reasons_if_delayed
count,5.000000e+03,5000.000000,5000,5000,5000.000000,5000.000000,5000,3098
unique,NaN,NaN,4962,4967,NaN,NaN,3,1
top,NaN,NaN,8/26/23 23:48,12/3/23 13:05,NaN,NaN,On Time,Traffic
freq,NaN,NaN,2,2,NaN,NaN,3470,3098
mean,5.029129e+09,50050.318200,NaN,NaN,4.443000,2.718048,NaN,NaN
std,2.863533e+09,28802.276922,NaN,NaN,8.063929,1.290306,NaN,NaN
min,6.046500e+04,43.000000,NaN,NaN,-5.000000,0.500000,NaN,NaN
25%,2.531421e+09,24928.500000,NaN,NaN,-1.000000,1.590000,NaN,NaN
50%,5.074378e+09,50262.500000,NaN,NaN,2.000000,2.690000,NaN,NaN
75%,7.488579e+09,74478.250000,NaN,NaN,8.000000,3.850000,NaN,NaN
max,9.998298e+09,99968.000000,NaN,NaN,30.000000,5.000000,NaN,NaN

In [20]:
df.isnull().sum()

order_id                    0
delivery_partner_id         0
promised_time               0
actual_time                 0
delivery_time_minutes       0
distance_km                 0
delivery_status             0
reasons_if_delayed       1902
dtype: int64

In [21]:
df.columns

Index(['order_id', 'delivery_partner_id', 'promised_time', 'actual_time',
       'delivery_time_minutes', 'distance_km', 'delivery_status',
       'reasons_if_delayed'],
      dtype='object')

In [22]:
df = pd.read_excel(r'D:\blinkit_project\docs\blinkit.xlsx',sheet_name='inventory')

df

       product_id      date  stock_received  damaged_stock
0            4452  03-18-23               0              2
1            4452  03-19-23               0              2
2            4452  03-21-23               0              2
3            4452  03-23-23               0              2
4            4452  03-26-23               0              2
...           ...       ...             ...            ...
75167      993331  10-28-24               4              0
75168      993331  10-29-24               3              0
75169      993331  10-31-24               0              2
75170      993331  02-11-24               0              2
75171      993331  05-11-24               4              0

[75172 rows x 4 columns]

In [23]:
df.head(10)

   product_id      date  stock_received  damaged_stock
0        4452  03-18-23               0              2
1        4452  03-19-23               0              2
2        4452  03-21-23               0              2
3        4452  03-23-23               0              2
4        4452  03-26-23               0              2
5        4452  03-27-23               3              0
6        4452  03-28-23               3              0
7        4452  02-04-23               3              0
8        4452  07-04-23               0              2
9        4452  08-04-23               3              0

In [24]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 75172 entries, 0 to 75171
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   product_id      75172 non-null  int64
 1   date            75172 non-null  object
 2   stock_received  75172 non-null  int64
 3   damaged_stock   75172 non-null  int64
dtypes: int64(3), object(1)
memory usage: 2.3+ MB

In [25]:
df.describe(include='all')

           product_id      date  stock_received  damaged_stock
count    75172.000000     75172    75172.000000   75172.000000
unique            NaN       600             NaN            NaN
top               NaN  04-06-23             NaN            NaN
freq              NaN       150             NaN            NaN
mean    514290.353097       NaN        1.962513       1.067791
std     291277.971875       NaN        1.639961       0.997706
min       4452.000000       NaN        0.000000       0.000000
25%     272170.000000       NaN        0.000000       0.000000
50%     542300.000000       NaN        3.000000       2.000000
75%     753354.000000       NaN        3.000000       2.000000
max     993331.000000       NaN        4.000000       2.000000

In [26]:
df.isnull().sum()

product_id        0
date              0
stock_received    0
damaged_stock     0
dtype: int64

### NO NULL VALUES IN INVENTORY DATA

In [27]:
df.columns

Index(['product_id', 'date', 'stock_received', 'damaged_stock'], dtype='object')

In [28]:
df = pd.read_excel(r'D:\blinkit_project\docs\blinkit.xlsx',sheet_name='marketing')

df

,campaign_id,campaign_name,date,target_audience,channel,impressions,clicks,conversions,spend,revenue_generated,roas
0,243,Referral Program,08-25-24,Premium,Email,2480,639,53,3641.18,5970.43,3.99
1,342,Flash Sale,08-08-23,New Users,Social Media,6335,277,43,2900.46,7711.31,2.34
2,417,Email Campaign,08-02-23,New Users,Social Media,9896,840,53,2704.17,5202.30,2.92
3,472,Festival Offer,05-25-24,New Users,Social Media,4729,128,95,1542.65,4316.40,3.29
4,648,New User Discount,11-04-23,All,Email,7368,138,43,4892.22,2261.53,2.35
...,...,...,...,...,...,...,...,...,...,...,...
5395,999216,App Push Notification,07-26-24,Premium,Social Media,6504,442,46,3885.79,5767.99,3.03
5396,999371,Flash Sale,01-02-24,All,Email,8809,139,83,4272.45,7206.68,2.46
5397,999377,Email Campaign,08-28-24,All,App,2864,622,55,4677.70,9655.34,2.98
5398,999683,New User Discount,04-28-24,All,App,9867,690,27,2386.45,4623.96,2.79
5399,999950,App Push Notification,03-23-23,New Users,SMS,2362,388,82,2454.03,4993.38,2.23

In [29]:
df.head(10)

,campaign_id,campaign_name,date,target_audience,channel,impressions,clicks,conversions,spend,revenue_generated,roas
0,243,Referral Program,08-25-24,Premium,Email,2480,639,53,3641.18,5970.43,3.99
1,342,Flash Sale,08-08-23,New Users,Social Media,6335,277,43,2900.46,7711.31,2.34
2,417,Email Campaign,08-02-23,New Users,Social Media,9896,840,53,2704.17,5202.30,2.92
3,472,Festival Offer,05-25-24,New Users,Social Media,4729,128,95,1542.65,4316.40,3.29
4,648,New User Discount,11-04-23,All,Email,7368,138,43,4892.22,2261.53,2.35
5,788,New User Discount,12-26-23,Premium,Email,3595,994,71,2896.44,4004.21,3.55
6,1005,Membership Drive,06-18-23,All,Email,8276,793,68,1189.21,9253.77,1.84
7,1604,Email Campaign,03-31-24,Premium,App,6379,502,89,3522.99,6315.41,3.53
8,1676,Email Campaign,08-08-23,Inactive,SMS,8311,894,73,3911.44,4606.78,1.67
9,1836,Membership Drive,04-13-23,All,App,4198,926,88,3265.42,7039.53,2.89

In [30]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5400 entries, 0 to 5399
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   campaign_id        5400 non-null   int64
 1   campaign_name      5400 non-null   object
 2   date               5400 non-null   object
 3   target_audience    5400 non-null   object
 4   channel            5400 non-null   object
 5   impressions        5400 non-null   int64
 6   clicks             5400 non-null   int64
 7   conversions        5400 non-null   int64
 8   spend              5400 non-null   float64
 9   revenue_generated  5400 non-null   float64
 10  roas               5400 non-null   float64
dtypes: float64(3), int64(4), object(4)
memory usage: 464.2+ KB

In [31]:
df.describe(include='all')

,campaign_id,campaign_name,date,target_audience,channel,impressions,clicks,conversions,spend,revenue_generated,roas
count,5400.000000,5400,5400,5400,5400,5400.000000,5400.000000,5400.000000,5400.000000,5400.000000,5400.000000
unique,NaN,9,600,4,4,NaN,NaN,NaN,NaN,NaN,NaN
top,NaN,Referral Program,08-25-24,New Users,App,NaN,NaN,NaN,NaN,NaN,NaN
freq,NaN,600,9,1356,1374,NaN,NaN,NaN,NaN,NaN,NaN
mean,501315.219074,NaN,NaN,NaN,NaN,5460.668519,550.767593,55.192222,3022.192267,5961.742106,2.740711
std,287611.524258,NaN,NaN,NaN,NaN,2571.779820,260.080051,26.150173,1148.732680,2322.242911,0.722986
min,243.000000,NaN,NaN,NaN,NaN,1002.000000,100.000000,10.000000,1000.630000,2003.100000,1.500000
25%,249200.000000,NaN,NaN,NaN,NaN,3231.500000,322.000000,32.000000,2029.070000,3907.240000,2.120000
50%,505012.500000,NaN,NaN,NaN,NaN,5457.500000,555.000000,55.000000,3042.485000,5935.940000,2.725000
75%,752219.250000,NaN,NaN,NaN,NaN,7676.250000,772.000000,78.000000,4011.572500,7973.712500,3.370000
max,999950.000000,NaN,NaN,NaN,NaN,9999.000000,1000.000000,100.000000,4997.550000,9999.540000,4.000000

In [32]:
df.isnull().sum()

campaign_id          0
campaign_name        0
date                 0
target_audience      0
channel              0
impressions          0
clicks               0
conversions          0
spend                0
revenue_generated    0
roas                 0
dtype: int64

### NO NULL VALUES IN  MARKETING DATA

In [33]:
df.columns

Index(['campaign_id', 'campaign_name', 'date', 'target_audience', 'channel',
       'impressions', 'clicks', 'conversions', 'spend', 'revenue_generated',
       'roas'],
      dtype='object')

In [34]:
df = pd.read_excel(r'D:\blinkit_project\docs\blinkit.xlsx',sheet_name='orders')

df

,order_id,customer_id,order_date,promised_delivery_time,actual_delivery_time,delivery_status,order_total,payment_method,delivery_partner_id,store_id
0,60465,15808945,10/23/24 5:23,10/23/24 5:33,10/23/24 5:39,On Time,589.47,UPI,58998,3943
1,2237858,48281892,4/2/23 3:45,4/2/23 4:00,4/2/23 4:02,On Time,3835.26,Wallet,97945,1987
2,3101265,89617089,5/23/24 3:20,5/23/24 3:36,5/23/24 3:40,On Time,3567.73,UPI,20246,974
3,5120698,44174426,6/9/23 12:09,6/9/23 12:24,6/9/23 12:40,Slightly Delayed,3064.36,Wallet,48582,3184
4,5512907,51476157,4/30/23 20:51,4/30/23 21:11,4/30/23 21:26,Slightly Delayed,861.53,Wallet,44545,419
...,...,...,...,...,...,...,...,...,...,...
4995,9993542681,42589311,5/23/23 4:12,5/23/23 4:25,5/23/23 4:41,Slightly Delayed,3564.26,UPI,73532,4596
4996,9996182478,39976965,4/18/23 13:12,4/18/23 13:30,4/18/23 13:30,On Time,340.36,UPI,48495,2861
4997,9997121955,46623192,4/21/24 0:02,4/21/24 0:18,4/21/24 0:15,On Time,1756.40,UPI,27103,6589
4998,9997994965,13796199,12/27/23 14:01,12/27/23 14:19,12/27/23 14:17,On Time,2780.28,Card,28092,4117
4999,9998297778,7728406,9/22/23 17:06,9/22/23 17:26,9/22/23 17:26,On Time,2833.20,Card,15629,5907

In [35]:
df.head(10)

,order_id,customer_id,order_date,promised_delivery_time,actual_delivery_time,delivery_status,order_total,payment_method,delivery_partner_id,store_id
0,60465,15808945,10/23/24 5:23,10/23/24 5:33,10/23/24 5:39,On Time,589.47,UPI,58998,3943
1,2237858,48281892,4/2/23 3:45,4/2/23 4:00,4/2/23 4:02,On Time,3835.26,Wallet,97945,1987
2,3101265,89617089,5/23/24 3:20,5/23/24 3:36,5/23/24 3:40,On Time,3567.73,UPI,20246,974
3,5120698,44174426,6/9/23 12:09,6/9/23 12:24,6/9/23 12:40,Slightly Delayed,3064.36,Wallet,48582,3184
4,5512907,51476157,4/30/23 20:51,4/30/23 21:11,4/30/23 21:26,Slightly Delayed,861.53,Wallet,44545,419
5,7550508,93127511,10/20/23 10:54,10/20/23 11:06,10/20/23 11:06,On Time,1067.68,Card,38073,70
6,8701796,14479168,8/19/24 19:00,8/19/24 19:14,8/19/24 19:23,Slightly Delayed,215.65,Cash,41266,1925
7,9408428,31456752,8/30/23 13:34,8/30/23 13:54,8/30/23 13:50,On Time,1911.86,UPI,76392,9889
8,10161194,63238941,12/24/23 23:10,12/24/23 23:28,12/24/23 23:30,On Time,3827.54,Card,58293,6592
9,10448052,90021871,8/5/23 10:00,8/5/23 10:21,8/5/23 10:25,On Time,1228.86,UPI,47308,1064

In [36]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 10 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   order_id                5000 non-null   int64
 1   customer_id             5000 non-null   int64
 2   order_date              5000 non-null   object
 3   promised_delivery_time  5000 non-null   object
 4   actual_delivery_time    5000 non-null   object
 5   delivery_status         5000 non-null   object
 6   order_total             5000 non-null   float64
 7   payment_method          5000 non-null   object
 8   delivery_partner_id     5000 non-null   int64
 9   store_id                5000 non-null   int64
dtypes: float64(1), int64(4), object(5)
memory usage: 390.8+ KB

In [37]:
df.describe(include='all')

,order_id,customer_id,order_date,promised_delivery_time,actual_delivery_time,delivery_status,order_total,payment_method,delivery_partner_id,store_id
count,5.000000e+03,5.000000e+03,5000,5000,5000,5000,5000.00000,5000,5000.000000,5000.000000
unique,NaN,NaN,4967,4962,4967,3,NaN,4,NaN,NaN
top,NaN,NaN,11/29/23 5:51,8/26/23 23:48,12/3/23 13:05,On Time,NaN,Card,NaN,NaN
freq,NaN,NaN,3,2,2,3470,NaN,1285,NaN,NaN
mean,5.029129e+09,5.009685e+07,NaN,NaN,NaN,NaN,2201.86170,NaN,50050.318200,4999.689000
std,2.863533e+09,2.919082e+07,NaN,NaN,NaN,NaN,1303.02438,NaN,28802.276922,2886.089242
min,6.046500e+04,3.181300e+04,NaN,NaN,NaN,NaN,13.25000,NaN,43.000000,1.000000
25%,2.531421e+09,2.404314e+07,NaN,NaN,NaN,NaN,1086.21500,NaN,24928.500000,2509.250000
50%,5.074378e+09,4.997808e+07,NaN,NaN,NaN,NaN,2100.69000,NaN,50262.500000,4987.000000
75%,7.488579e+09,7.621215e+07,NaN,NaN,NaN,NaN,3156.88250,NaN,74478.250000,7500.750000
max,9.998298e+09,9.989390e+07,NaN,NaN,NaN,NaN,6721.46000,NaN,99968.000000,9995.000000

In [38]:
df.isnull().sum()

order_id                  0
customer_id               0
order_date                0
promised_delivery_time    0
actual_delivery_time      0
delivery_status           0
order_total               0
payment_method            0
delivery_partner_id       0
store_id                  0
dtype: int64

### NO NULL VALUES IN ORDER DATE

In [39]:
df.columns

Index(['order_id', 'customer_id', 'order_date', 'promised_delivery_time',
       'actual_delivery_time', 'delivery_status', 'order_total',
       'payment_method', 'delivery_partner_id', 'store_id'],
      dtype='object')

In [40]:
df = pd.read_excel(r'D:\blinkit_project\docs\blinkit.xlsx',sheet_name='order_items')

df

        order_id  product_id  quantity  unit_price
0          60465      361361         2      826.21
1        2237858      585299         1      799.46
2        3101265      300159         1       44.35
3        5120698      187399         1       53.49
4        5512907      659290         3      319.34
...          ...         ...       ...         ...
4995  9993542681      880510         1      951.43
4996  9996182478      592784         3      280.35
4997  9997121955      739534         2      994.56
4998  9997994965      461804         2      310.69
4999  9998297778      709916         3       33.76

[5000 rows x 4 columns]

In [41]:
df.head(10)

   order_id  product_id  quantity  unit_price
0     60465      361361         2      826.21
1   2237858      585299         1      799.46
2   3101265      300159         1       44.35
3   5120698      187399         1       53.49
4   5512907      659290         3      319.34
5   7550508      140154         2      171.20
6   8701796      672059         2      672.73
7   9408428      124290         1       39.65
8  10161194      382511         1      702.54
9  10448052      945635         2      778.90

In [42]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   order_id    5000 non-null   int64
 1   product_id  5000 non-null   int64
 2   quantity    5000 non-null   int64
 3   unit_price  5000 non-null   float64
dtypes: float64(1), int64(3)
memory usage: 156.4 KB

In [43]:
df.describe(include='all')

           order_id     product_id     quantity   unit_price
count  5.000000e+03    5000.000000  5000.000000  5000.000000
mean   5.029129e+09  509974.939600     2.006800   493.157900
std    2.863533e+09  293678.307475     0.820542   298.075647
min    6.046500e+04    4452.000000     1.000000    12.320000
25%    2.531421e+09  257719.000000     1.000000   227.220000
50%    5.074378e+09  540618.000000     2.000000   448.160000
75%    7.488579e+09  747801.000000     3.000000   781.080000
max    9.998298e+09  993331.000000     3.000000   995.980000

In [44]:
df.isnull().sum()

order_id      0
product_id    0
quantity      0
unit_price    0
dtype: int64

### NO NULL VALUES IN  ORDER_ITEMS DATA

In [45]:
df.columns

Index(['order_id', 'product_id', 'quantity', 'unit_price'], dtype='object')

In [46]:
df = pd.read_excel(r'D:\blinkit_project\docs\blinkit.xlsx',sheet_name='products')

df

,product_id,product_name,category,brand,price,mrp,margin_percentage,shelf_life_days,min_stock_level,max_stock_level
0,4452,Baby Wipes,Baby Care,Morar-Mistry,169.88,242.69,30,365,27,100
1,6405,Baby Food,Baby Care,Kashyap-Reddy,236.51,337.87,30,365,11,81
2,9436,Toothpaste,Personal Care,Naidu PLC,88.43,136.05,35,365,19,76
3,11422,Potatoes,Fruits & Vegetables,Ramaswamy-Tata,127.16,169.55,25,3,20,65
4,14145,Spinach,Fruits & Vegetables,"Thakur, Shah and Pingle",630.84,841.12,25,3,14,53
...,...,...,...,...,...,...,...,...,...,...
263,970529,Diapers,Baby Care,"Kurian, Patla and Sanghvi",827.44,1182.06,30,365,19,84
264,990993,Chocolates,Snacks & Munchies,Guha-Subramaniam,263.70,405.69,35,90,22,61
265,991434,Cookies,Snacks & Munchies,Mital-Oza,237.62,365.57,35,90,12,87
266,992178,Pain Reliever,Pharmacy,Basu and Sons,632.43,790.54,20,365,16,89
267,993331,Pulses,Grocery & Staples,"Parmer, Gola and Yogi",102.44,120.52,15,365,28,86

In [47]:
df.head(10)

,product_id,product_name,category,brand,price,mrp,margin_percentage,shelf_life_days,min_stock_level,max_stock_level
0,4452,Baby Wipes,Baby Care,Morar-Mistry,169.88,242.69,30,365,27,100
1,6405,Baby Food,Baby Care,Kashyap-Reddy,236.51,337.87,30,365,11,81
2,9436,Toothpaste,Personal Care,Naidu PLC,88.43,136.05,35,365,19,76
3,11422,Potatoes,Fruits & Vegetables,Ramaswamy-Tata,127.16,169.55,25,3,20,65
4,14145,Spinach,Fruits & Vegetables,"Thakur, Shah and Pingle",630.84,841.12,25,3,14,53
5,15314,Cheese,Dairy & Breakfast,Banik-Ratta,578.85,723.56,20,7,30,91
6,18035,Dish Soap,Household Care,Ramesh Inc,968.94,1291.92,25,365,12,87
7,26060,Vitamins,Pharmacy,Shah and Sons,342.94,428.67,20,365,25,57
8,33797,Pain Reliever,Pharmacy,Gaba LLC,888.12,1110.15,20,365,12,51
9,33955,Frozen Pizza,Instant & Frozen Food,Baral Group,186.08,310.13,40,180,29,84

In [48]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 268 entries, 0 to 267
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   product_id         268 non-null    int64
 1   product_name       268 non-null    object
 2   category           268 non-null    object
 3   brand              268 non-null    object
 4   price              268 non-null    float64
 5   mrp                268 non-null    float64
 6   margin_percentage  268 non-null    int64
 7   shelf_life_days    268 non-null    int64
 8   min_stock_level    268 non-null    int64
 9   max_stock_level    268 non-null    int64
dtypes: float64(2), int64(5), object(3)
memory usage: 21.1+ KB

In [49]:
df['margin_percentage'] = df['margin_percentage'].astype('float64')

In [50]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 268 entries, 0 to 267
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   product_id         268 non-null    int64
 1   product_name       268 non-null    object
 2   category           268 non-null    object
 3   brand              268 non-null    object
 4   price              268 non-null    float64
 5   mrp                268 non-null    float64
 6   margin_percentage  268 non-null    float64
 7   shelf_life_days    268 non-null    int64
 8   min_stock_level    268 non-null    int64
 9   max_stock_level    268 non-null    int64
dtypes: float64(3), int64(4), object(3)
memory usage: 21.1+ KB

In [51]:
df.describe(include='all')

,product_id,product_name,category,brand,price,mrp,margin_percentage,shelf_life_days,min_stock_level,max_stock_level
count,268.000000,268,268,268,268.000000,268.000000,268.000000,268.000000,268.000000,268.000000
unique,NaN,51,11,267,NaN,NaN,NaN,NaN,NaN,NaN
top,NaN,Pet Treats,Dairy & Breakfast,Jha Group,NaN,NaN,NaN,NaN,NaN,NaN
freq,NaN,12,30,2,NaN,NaN,NaN,NaN,NaN,NaN
mean,514855.940299,NaN,NaN,NaN,488.356828,680.434739,27.779851,231.757463,20.388060,74.753731
std,291391.529820,NaN,NaN,NaN,298.487200,419.772224,7.458753,151.205830,5.958546,14.591535
min,4452.000000,NaN,NaN,NaN,12.320000,17.600000,15.000000,3.000000,10.000000,50.000000
25%,273697.750000,NaN,NaN,NaN,226.717500,325.150000,20.000000,90.000000,15.000000,63.750000
50%,541459.000000,NaN,NaN,NaN,442.185000,616.970000,30.000000,365.000000,21.000000,73.000000
75%,754334.000000,NaN,NaN,NaN,779.445000,1056.620000,35.000000,365.000000,25.250000,88.000000
max,993331.000000,NaN,NaN,NaN,995.980000,1633.320000,40.000000,365.000000,30.000000,100.000000

In [52]:
df.isnull().sum()

product_id           0
product_name         0
category             0
brand                0
price                0
mrp                  0
margin_percentage    0
shelf_life_days      0
min_stock_level      0
max_stock_level      0
dtype: int64

### NO NULL VALUES IN PRODUCTS DATA

In [53]:
df.columns

Index(['product_id', 'product_name', 'category', 'brand', 'price', 'mrp',
       'margin_percentage', 'shelf_life_days', 'min_stock_level',
       'max_stock_level'],
      dtype='object')

In [64]:
!pip install pymysql sqlalchemy

Requirement already satisfied: pymysql in c:\users\damma\anaconda3\lib\site-packages (1.1.2)
Requirement already satisfied: sqlalchemy in c:\users\damma\anaconda3\lib\site-packages (2.0.43)
Requirement already satisfied: greenlet>=1 in c:\users\damma\anaconda3\lib\site-packages (from sqlalchemy) (3.2.4)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\damma\anaconda3\lib\site-packages (from sqlalchemy) (4.15.0)

In [81]:
sheet_table_map = {
    "customers": "customers",
    "customer_feedback": "customer_feedback",
    "delivery": "delivery",
    "inventory": "inventory",
    "marketing": "marketing",
    "orders": "orders",
    "order_items": "order_items",
    "products": "products"
}

In [82]:
from sqlalchemy import create_engine
import pandas as pd

username = "root"
password = "root"
host = "localhost"
port = "3306"
database = "blinkit_project"

engine = create_engine(
    f"mysql+pymysql://{username}:{password}@{host}:{port}/{database}"
)

In [83]:
excel_path = r"D:\blinkit_project\docs\blinkit.xlsx"   # change if needed

for sheet_name, table_name in sheet_table_map.items():
    df = pd.read_excel(excel_path, sheet_name=sheet_name)

    df.to_sql(
        table_name,
        engine,
        if_exists="replace",   # use "append" if you want incremental loads
        index=False
    )

    print(f"Inserted {len(df)} rows into `{table_name}`")

Inserted 2500 rows into `customers`
Inserted 5000 rows into `customer_feedback`
Inserted 5000 rows into `delivery`
Inserted 75172 rows into `inventory`
Inserted 5400 rows into `marketing`
Inserted 5000 rows into `orders`
Inserted 5000 rows into `order_items`
Inserted 268 rows into `products`

In [87]:
# pd.read_sql("SELECT * FROM customers LIMIT 5;", engine)
pd.read_sql("SELECT * FROM orders LIMIT 5;", engine)

,order_id,customer_id,order_date,promised_delivery_time,actual_delivery_time,delivery_status,order_total,payment_method,delivery_partner_id,store_id
0,60465,15808945,10/23/24 5:23,10/23/24 5:33,10/23/24 5:39,On Time,589.47,UPI,58998,3943
1,2237858,48281892,4/2/23 3:45,4/2/23 4:00,4/2/23 4:02,On Time,3835.26,Wallet,97945,1987
2,3101265,89617089,5/23/24 3:20,5/23/24 3:36,5/23/24 3:40,On Time,3567.73,UPI,20246,974
3,5120698,44174426,6/9/23 12:09,6/9/23 12:24,6/9/23 12:40,Slightly Delayed,3064.36,Wallet,48582,3184
4,5512907,51476157,4/30/23 20:51,4/30/23 21:11,4/30/23 21:26,Slightly Delayed,861.53,Wallet,44545,419